### ISSUE TITLE
Bro the get_server_server is not working so pls fix it

### ISSUE THREAD

**Issue by BishoyHanyRaafat** [mytja/PloudOS-API#2]
Tbh I am a fun of this repo and I used it a lot but now I can PLS FIX IT!!!!

**Comment by mytja** [comment]
First things first, you haven't provided any details of your issue. What you're saying is just "oh, i have an issue pls fix it". How am I supposed to know, out of all possibilities, what went wrong with the code if you don't provide me the stacktrace.

Also, this project was primarily built for my (private/personal) project and I open sourced it only because I thought it would be useful to other people.

And last but not the least, I'm not going to tolerate such a disrespectful behaviour towards maintainers. If you want it fixed, fix it yourself or at least be a little bit polite. I mean, you should not open an issue with saying only something like this: `bro, i had fun with this repo but now something no work PLS FIX NOW`. Firstly, I hate being called a "bro" by random people. You have also DEMANDED a fix instead of politely requesting it (in which case I'd probably fix it if you would've given me proper stacktrace) or maybe, I don't know, fixing it YOURSELF.

Open a new (polite) issue or don't use this project ever again.
